gazebo_ros_control:
  pid_gains:
    panda_1_joint1: {p: 50, i: 0, d: 20}
    panda_1_joint2: {p: 10000, i: 0, d: 500}
    panda_1_joint3: {p: 100, i: 0, d: 10}
    panda_1_joint4: {p: 1000, i: 0, d: 50}
    panda_1_joint5: {p: 100, i: 0, d: 10}
    panda_1_joint6: {p: 100, i: 0, d: 10}
    panda_1_joint7: {p: 10, i: 0.5, d: 0.1}
    panda_1_finger_joint1: {p: 100, i: 0, d: 50}
    panda_1_finger_joint2: {p: 100, i: 0, d: 50}

    panda_2_joint1: {p: 50, i: 0, d: 20}
    panda_2_joint2: {p: 10000, i: 0, d: 500}
    panda_2_joint3: {p: 100, i: 0, d: 10}
    panda_2_joint4: {p: 1000, i: 0, d: 50}
    panda_2_joint5: {p: 100, i: 0, d: 10}
    panda_2_joint6: {p: 100, i: 0, d: 10}
    panda_2_joint7: {p: 10, i: 0.5, d: 0.1}
    panda_2_finger_joint1: {p: 100, i: 0, d: 50}
    panda_2_finger_joint2: {p: 100, i: 0, d: 50}
